### ISSUE TITLE
2枚以上のプロペラの設定

### ISSUE THREAD

**Issue by HAPSRG** [UTokyoTsuchiyaLAB/UNLSI#14]
2枚以上のプロペラを設定しようとすると、先に設定したほうのpropRHSの行列サイズが適切でなくなる。
（あとのプロペラのIDが正しく設定される前に方程式を作成してしまうため）

**Comment by NaotoMoritaUT** [comment]
次バージョンでは一括設定できるようにする。また、関数実行ごとにpropRHSはすべて作り直す

**Comment by NaotoMoritaUT** [comment]
変更した
