### ISSUE TITLE
calcDyncoefのコメント修正

### ISSUE THREAD

**Issue by tagyasu** [UTokyoTsuchiyaLAB/UNLSI#2]
・DYNCOEFに関する説明のコメントが古い
・p,q,rに関する微分が有次元かつradになっているので説明を追記したい

**Comment by NaotoMoritaUT** [comment]
pqr微分は無次元になっているはず。

**Comment by tagyasu** [comment]
UNLSI.ｍの1649行から1659行では無次元化の処理が見当たらないのですが，ほかのところで処理されているのでしょうか？

`omegadwf(jter) = omegadwf(jter)+dw.*180./pi;
omegadwr(jter) = omegadwr(jter)-dw.*180./pi;
obj.settingUNLSI.angularVelocity = repmat(omegadwf,[numel(alpha),1]);
AERODATAf = obj.solveFlowForAdjoint(u0+udwf(:,2+jter),flowNo,alpha,beta);
obj.settingUNLSI.angularVelocity = repmat(omegadwr,[numel(alpha),1]);
AERODATAr = obj.solveFlowForAdjoint(u0-udwr(:,2+jter),flowNo,alpha,beta);
obj.settingUNLSI.angularVelocity = avorg;
tmp = (AERODATAf{flowNo} - AERODATAr{flowNo})./(2*dw*nondim(jter));
for i = 1:size(AERODATAf{flowNo},1)
    obj.DYNCOEF{flowNo,i}(:,3+jter) = tmp(i,ind)'; % pqr
end`

**Comment by NaotoMoritaUT** [comment]
nindimで割っているところが該当します。
ちょっと分かりにくいですね、、

**Comment by tagyasu** [comment]
確認不足でした．ありがとうございます．

> nondim = [obj.BREF/(2*1),obj.CREF/(2*1),obj.BREF/(2*1)];

だと飛行速度が反映されていないのは大丈夫でしょうか？

**Comment by NaotoMoritaUT** [comment]
パネル法の主流速度は1だからこれでOK。

**Comment by tagyasu** [comment]
わかりました．ありがとうございます．

**Comment by tagyasu** [comment]
わかりました．ありがとうございます．
